"""remove

Revision ID: 5438375a44ea
Revises: 1faaf34f5b07
Create Date: 2024-05-26 01:41:25.874308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5438375a44ea'
down_revision: Union[str, None] = '1faaf34f5b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plano', sa.Column('aporte', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plano', 'aporte')
    # ### end Alembic commands ###
