"""add table initial

Revision ID: d41670a2e090
Revises: 
Create Date: 2024-05-25 21:18:37.817594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd41670a2e090'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataDeNascimento', sa.DateTime(), nullable=False),
    sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rendaMensal', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('produto',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('susep', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiracaoDeVenda', sa.DateTime(), nullable=False),
    sa.Column('valorMinimoAporteInicial', sa.Numeric(), nullable=False),
    sa.Column('valorMinimoAporteExtra', sa.Numeric(), nullable=False),
    sa.Column('idadeDeEntrada', sa.Integer(), nullable=False),
    sa.Column('idadeDeSaida', sa.Integer(), nullable=False),
    sa.Column('carenciaInicialDeResgate', sa.Integer(), nullable=False),
    sa.Column('carenciaEntreResgates', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_id'), 'produto', ['id'], unique=False)
    op.create_table('plano',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('idCliente', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('idProduto', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dataDaContratacao', sa.DateTime(), nullable=False),
    sa.Column('idadeDeAposentadoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['idProduto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plano_id'), 'plano', ['id'], unique=False)
    op.create_table('aporteextra',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('idCliente', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('idPlano', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('valorAporte', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['idPlano'], ['plano.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aporteextra_id'), 'aporteextra', ['id'], unique=False)
    op.create_table('resgate',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('idPlano', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('valorResgate', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['idPlano'], ['plano.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resgate_id'), 'resgate', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resgate_id'), table_name='resgate')
    op.drop_table('resgate')
    op.drop_index(op.f('ix_aporteextra_id'), table_name='aporteextra')
    op.drop_table('aporteextra')
    op.drop_index(op.f('ix_plano_id'), table_name='plano')
    op.drop_table('plano')
    op.drop_index(op.f('ix_produto_id'), table_name='produto')
    op.drop_table('produto')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
